spring:
  profiles.active: zone1
  application:
    name: vaadin
  main:
    allow-circular-references: 'true'
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: myrealm
  public-client: 'true'
  resource: vaadin
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
    availability-zones:
      region-1: zone1,zone2
