spring:
  application:
    name: vaadin
  main:
    allow-circular-references: 'true'
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: myrealm
  public-client: 'true'
  resource: vaadin
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
